Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -7,58 +7,30 @@ pool:
 
 steps:
 
-# - task: VeracodeCommunityScaAdoExtension@1
-#   inputs:
-#     scanType: 'directory'
-#     scanTarget: '$(Build.SourcesDirectory)'
-#     minCVSS: '5'
-#     failBuild: true
-#   env:
-#     SRCCLR_API_TOKEN: $(SECRET)
-
-# Step 1: Package Binaries
-# - task: CmdLine@2
-#   displayName: Package Artifacts
-#   inputs:
-#     script: |
-#       curl -fsS https://tools.veracode.com/veracode-cli/install | sh
-#       ./veracode package --source $(Build.SourcesDirectory) --output $(Build.ArtifactStagingDirectory)/artifacts --trust
-  
-#   env: 
-#       VERACODE_API_KEY_ID: 'fa'
-#       VERACODE_API_KEY_SECRET: '2f'
-
-
-# Step 2: Archive Packaged Binaries
-- task: ArchiveFiles@2
-  displayName: Archive Packaged Binaries
+- task: Bash@3
+  displayName: 'Install Veracode CLI and Package Scan'
   inputs:
-    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
-    includeRootFolder: true
-    archiveType: 'zip'
-    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
-    replaceExistingArchive: true
+    targetType: 'inline'
+    script: |
+      curl -fsS https://tools.veracode.com/veracode-cli/install | sh
+      ./veracode package -das $(Build.SourcesDirectory) --output ./verascan
 
-# Step 3: Publish the Archived File
+      # Check if the verascan directory exists
+      if [ ! -d "verascan" ]; then
+        echo "Error: verascan directory not found."
+        exit 1
+      fi
+
 - task: PublishBuildArtifacts@1
-  displayName: Publish Packaged Binaries
+  displayName: 'Publish Verascan Artifact'
   inputs:
-    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
-    ArtifactName: 'packaged-binaries'
-    publishLocation: 'Container'
-
-# Step 4: Download the Archived File
-- task: DownloadPipelineArtifact@2
-  displayName: Download Packaged Binaries
-  inputs:
-    buildType: 'current'
-    artifact: 'packaged-binaries'
-    path: '$(Pipeline.Workspace)'
+    pathToPublish: 'verascan'
+    artifactName: 'VeracodeScanResults'
 
 - task: VeracodePipelineScan@0
   inputs:
     serviceConnection: 'Veracode-Arun-GM'
-    fileToScan: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
+    fileToScan: 'verascan'
     policyName: 'Al-Test'
 
 
